### ISSUE TITLE
Improve GUI

### ISSUE THREAD

**Issue by akshgpt7** [Marauders-9998/Attendance-Management-using-Face-Recognition#12]
The current GUI looks very basic and not so vibrant. It'll be better to interact with a nicer GUI.

**Comment by Vibhu-Agarwal** [comment]
Thanks for the feedback @akshgpt7 
Since the discussion regarding this is already open in this issue #11, you can give your ideas on how you can contribute to the project to improve its UI.
Also if you upvote the issue, we'll create a seperate repository specifically for this idea where you can have your PRs merged.
I'll close this issue on the note that you'll be following the further discussion on #11
