### ISSUE TITLE
how to enter student portal ????

### ISSUE THREAD

**Issue by sahiljhalera** [Marauders-9998/Attendance-Management-using-Face-Recognition#8]
i tried to  enter student portal with batch name, student name and password ubuntu but it shows incorrect fillings . please help

**Comment by Vibhu-Agarwal** [comment]
Hi @sahiljhalera 
Welcome to Open Source and thanks for opening this issue.
Check if you're entering the correct credentials.
The credentials are currently hard-coded in the app.
You can find it here
https://github.com/Marauders-9998/Attendance-Management-using-Face-Recognition/blob/39cce2901e00e716b7c65db370e5f7b0c18453de/Attendance_app.py#L22-L24

If the problem still, persists, you can submit another issue regarding the bug, explaining how to reproduce it along with the environment in which the bug is produced.
